CREATE TABLE order_products (
  id SERIAL PRIMARY KEY,
  quantity INTEGER DEFAULT 1 NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE NOT NULL
);